"use client";

import React, { useState, useEffect } from 'react';
import { createClient } from '@supabase/supabase-js';
import { Search, Mail, Send, CheckCircle, Clock, AlertCircle, Bot, Trash2 } from 'lucide-react';

// Initialize Supabase Client
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';
const supabase = createClient(supabaseUrl, supabaseAnonKey);

export default function OutlookDashboard() {
  const [conversations, setConversations] = useState<any[]>([]);
  const [messages, setMessages] = useState<any[]>([]);
  const [selectedConv, setSelectedConv] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [aiDrafting, setAiDrafting] = useState(false);

  // Fetch conversations on load
  useEffect(() => {
    fetchConversations();
  }, []);

  async function fetchConversations() {
    setLoading(true);
    const { data, error } = await supabase
      .from('conversations')
      .select('*')
      .order('last_received_at', { ascending: false });

    if (!error && data) setConversations(data);
    setLoading(false);
  }

  async function fetchMessages(convId: string) {
    const { data, error } = await supabase
      .from('messages')
      .select('*')
      .eq('external_conv_id', convId)
      .order('received_at', { ascending: true });

    if (!error && data) setMessages(data);
  }

  async function generateAiDraft(conv: any) {
    setAiDrafting(true);
    const lastMessage = messages[messages.length - 1]?.body_plain || "";
    
    try {
      // Direct call to Groq API via proxy or serverless function
      // For this prototype, we'll write directly to the queue to simulate AI intent
      const { error } = await supabase
        .from('automation_queue')
        .insert([{
          external_conv_id: conv.external_conv_id,
          original_msg_id: messages[messages.length - 1]?.external_msg_id,
          suggested_subject: `Re: ${conv.subject}`,
          suggested_body: "Generated by AI: Thank you for your message. I have received your inquiry and am looking into it. I will get back to you shortly.",
          status: 'PENDING_APPROVAL'
        }]);

      if (!error) {
        alert("AI Draft generated and added to the Approval Queue.");
      }
    } catch (err) {
      console.error(err);
    } finally {
      setAiDrafting(false);
    }
  }

  async function approveDraft(convId: string) {
    const { error } = await supabase
      .from('automation_queue')
      .update({ status: 'APPROVED' })
      .eq('external_conv_id', convId)
      .eq('status', 'PENDING_APPROVAL');

    if (!error) alert("Approved! The Excel VBA Agent will send this on the next sync.");
  }

  return (
    <div className="flex h-screen bg-slate-50 font-sans">
      {/* Sidebar: Conversation List */}
      <div className="w-1/3 border-r bg-white overflow-y-auto">
        <div className="p-4 border-b bg-slate-900 text-white flex justify-between items-center">
          <h1 className="font-bold text-lg">Conversation Manager</h1>
          <button onClick={fetchConversations} className="p-1 hover:bg-slate-700 rounded">
            <Clock size={18} />
          </button>
        </div>
        
        {loading ? (
          <div className="p-10 text-center text-slate-400">Loading Tunnel Data...</div>
        ) : (
          conversations.map((conv) => (
            <div 
              key={conv.id} 
              onClick={() => { setSelectedConv(conv); fetchMessages(conv.external_conv_id); }}
              className={`p-4 border-b cursor-pointer hover:bg-slate-50 transition-colors ${selectedConv?.id === conv.id ? 'bg-blue-50 border-l-4 border-l-blue-600' : ''}`}
            >
              <div className="flex justify-between items-start mb-1">
                <span className="font-semibold text-slate-800 truncate w-48">{conv.vendor_name || "Unknown Vendor"}</span>
                <span className="text-xs text-slate-400">
                  {new Date(conv.last_received_at || conv.created_at).toLocaleDateString()}
                </span>
              </div>
              <div className="text-sm text-slate-600 truncate">{conv.subject}</div>
            </div>
          ))
        )}
      </div>

      {/* Main Content: Message Preview & Actions */}
      <div className="flex-1 flex flex-col overflow-hidden">
        {selectedConv ? (
          <>
            <div className="p-6 border-b bg-white flex justify-between items-center shadow-sm">
              <div>
                <h2 className="text-xl font-bold text-slate-800">{selectedConv.subject}</h2>
                <p className="text-sm text-slate-500">ID: {selectedConv.external_conv_id}</p>
              </div>
              <div className="flex gap-2">
                <button 
                  onClick={() => generateAiDraft(selectedConv)}
                  disabled={aiDrafting}
                  className="flex items-center gap-2 bg-purple-600 text-white px-4 py-2 rounded-lg hover:bg-purple-700 disabled:opacity-50"
                >
                  <Bot size={18} /> {aiDrafting ? 'Drafting...' : 'AI Draft'}
                </button>
                <button 
                  onClick={() => approveDraft(selectedConv.external_conv_id)}
                  className="flex items-center gap-2 bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700"
                >
                  <CheckCircle size={18} /> Approve for VBA
                </button>
              </div>
            </div>

            <div className="flex-1 overflow-y-auto p-6 space-y-4">
              {messages.map((msg) => (
                <div key={msg.id} className={`flex ${msg.direction === 'Outbound' ? 'justify-end' : 'justify-start'}`}>
                  <div className={`max-w-2xl p-4 rounded-2xl shadow-sm ${msg.direction === 'Outbound' ? 'bg-blue-600 text-white' : 'bg-white border'}`}>
                    <div className="text-xs mb-2 opacity-70">
                      {msg.sender_email} • {new Date(msg.received_at).toLocaleString()}
                    </div>
                    <div className="text-sm leading-relaxed">{msg.body_plain}</div>
                  </div>
                </div>
              ))}
            </div>
          </>
        ) : (
          <div className="flex-1 flex flex-col items-center justify-center text-slate-400">
            <Mail size={48} className="mb-4 opacity-20" />
            <p>Select a conversation from the tunnel to begin review.</p>
          </div>
        )}
      </div>
    </div>
  );
}
